# Generated by Django 3.2.25 on 2025-03-25 17:49

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_group_subgroup_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='group_id',
            field=models.ForeignKey(default=core.models.Group.get_default_group_pk, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_id',
            field=models.ForeignKey(default=core.models.Venue.get_default_venue_pk, on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='group_id',
            field=models.ForeignKey(default=core.models.Group.get_default_group_pk, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='subgroup_id',
            field=models.ForeignKey(default=core.models.SubGroup.get_default_subgroup_pk, on_delete=django.db.models.deletion.CASCADE, to='core.subgroup'),
        ),
    ]
